name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/kvnbbg/task-app
      PORT: 8000
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Lint PHP
        run: php -l index.php
      - name: Smoke Test
        run: |
          php -S localhost:$PORT index.php & sleep 5
          curl -f http://localhost:$PORT/
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}
